/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    works: Work;
    'journal-posts': JournalPost;
    'contact-inquiries': ContactInquiry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    works: WorksSelect<false> | WorksSelect<true>;
    'journal-posts': JournalPostsSelect<false> | JournalPostsSelect<true>;
    'contact-inquiries': ContactInquiriesSelect<false> | ContactInquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'studio-page': StudioPage;
    'works-page': WorksPage;
    'journal-page': JournalPage;
    'about-page': AboutPage;
    'contact-page': ContactPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'studio-page': StudioPageSelect<false> | StudioPageSelect<true>;
    'works-page': WorksPageSelect<false> | WorksPageSelect<true>;
    'journal-page': JournalPageSelect<false> | JournalPageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Create case studies that appear on /works and /works/[slug].
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works".
 */
export interface Work {
  id: number;
  /**
   * Project name (e.g. Casa Muse). Slug auto-fills from this.
   */
  title: string;
  /**
   * URL path: /works/[slug]
   */
  slug: string;
  /**
   * Client or brand name shown on the listing card.
   */
  client: string;
  /**
   * e.g. Interior Design, Skincare, Fine Jewellery
   */
  industry?: string | null;
  /**
   * Full-width image at the top of the case study page.
   */
  heroImage?: (number | null) | Media;
  /**
   * Introduce the brand. Who they are, what makes them special.
   */
  overview?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * What problem or opportunity brought them to you?
   */
  problem?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * How did you solve it? Multiple paragraphs welcome.
   */
  solution?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * List of deliverables (e.g. Brand Strategy, Social Content).
   */
  deliverables?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Outcomes and metrics (e.g. 42% engagement increase).
   */
  results?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional testimonial quote from the client.
   */
  feedback?: {
    /**
     * The quote text.
     */
    quote?: string | null;
    /**
     * e.g. Jane D., Founder of Casa Muse
     */
    attribution?: string | null;
  };
  /**
   * Images shown in the burgundy gallery section.
   */
  galleryImages?:
    | {
        image: number | Media;
        /**
         * Optional muted loop that plays in place of the image while the tile is on screen. The image above stays as its poster.
         */
        video?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Two images below The Brand section.
   */
  brandImages?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Series pill on the case study page.
   */
  seriesLabel?: string | null;
  /**
   * Tags shown on the /works card.
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Thumbnail for /works listing.
   */
  coverImage?: (number | null) | Media;
  /**
   * Optional short tagline for metadata.
   */
  tagline?: string | null;
  /**
   * Lower = appears first.
   */
  sortOrder?: number | null;
  /**
   * Date shown on the case study page.
   */
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-posts".
 */
export interface JournalPost {
  id: number;
  title: string;
  /**
   * URL-safe identifier. Used in /journal/[slug].
   */
  slug: string;
  /**
   * e.g. Branding, Strategy, Creative Obsession
   */
  category: string;
  /**
   * Estimated read time in minutes.
   */
  readTime?: number | null;
  /**
   * Shown in the meta pill as "By {author}".
   */
  author?: string | null;
  /**
   * Short summary shown on the Journal listing grid.
   */
  excerpt?: string | null;
  /**
   * Subtitle shown below the article title on the post page.
   */
  deck?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * Write your article here. Supports headings, paragraphs, images, and links.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Optional structured layout. Only used if Article Content above is empty.
   */
  articleBlocks?:
    | (
        | {
            items?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'paragraphs';
          }
        | {
            heading: string;
            paragraphs?:
              | {
                  text: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'headingGroup';
          }
        | {
            media: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            /**
             * Number of images per row
             */
            columns?: ('2' | '3' | '4') | null;
            images?:
              | {
                  media: number | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'imageGrid';
          }
        | {
            /**
             * Opening sentence in full opacity.
             */
            lead: string;
            /**
             * Middle sentence shown at reduced opacity.
             */
            muted: string;
            /**
             * Closing sentence in full opacity.
             */
            end: string;
            ctaLabel: string;
            ctaHref: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'closingCta';
          }
      )[]
    | null;
  publishedAt: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-inquiries".
 */
export interface ContactInquiry {
  id: number;
  name: string;
  email: string;
  /**
   * Legacy subject field. Kept for older submissions.
   */
  subject?: string | null;
  /**
   * Legacy message field (nullable). New form submissions may store a readable summary here.
   */
  message?: string | null;
  service?: string | null;
  brandName?: string | null;
  socialLink?: string | null;
  challenge?: string | null;
  brandGoal?: string | null;
  timeline?: string | null;
  referralSource?: string | null;
  additionalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'works';
        value: number | Work;
      } | null)
    | ({
        relationTo: 'journal-posts';
        value: number | JournalPost;
      } | null)
    | ({
        relationTo: 'contact-inquiries';
        value: number | ContactInquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works_select".
 */
export interface WorksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  client?: T;
  industry?: T;
  heroImage?: T;
  overview?: T;
  problem?: T;
  solution?: T;
  deliverables?:
    | T
    | {
        item?: T;
        id?: T;
      };
  results?:
    | T
    | {
        item?: T;
        id?: T;
      };
  feedback?:
    | T
    | {
        quote?: T;
        attribution?: T;
      };
  galleryImages?:
    | T
    | {
        image?: T;
        video?: T;
        id?: T;
      };
  brandImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  seriesLabel?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  coverImage?: T;
  tagline?: T;
  sortOrder?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-posts_select".
 */
export interface JournalPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  readTime?: T;
  author?: T;
  excerpt?: T;
  deck?: T;
  heroImage?: T;
  body?: T;
  articleBlocks?:
    | T
    | {
        paragraphs?:
          | T
          | {
              items?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        headingGroup?:
          | T
          | {
              heading?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              media?: T;
              id?: T;
              blockName?: T;
            };
        imageGrid?:
          | T
          | {
              columns?: T;
              images?:
                | T
                | {
                    media?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        closingCta?:
          | T
          | {
              lead?: T;
              muted?: T;
              end?: T;
              ctaLabel?: T;
              ctaHref?: T;
              id?: T;
              blockName?: T;
            };
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-inquiries_select".
 */
export interface ContactInquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  subject?: T;
  message?: T;
  service?: T;
  brandName?: T;
  socialLink?: T;
  challenge?: T;
  brandGoal?: T;
  timeline?: T;
  referralSource?: T;
  additionalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  location?: string | null;
  email?: string | null;
  phone?: string | null;
  /**
   * URL for the 'Book a Discovery Call' CTA button in the nav.
   */
  bookingLink?: string | null;
  /**
   * Main navigation links (Studio, Works, Journal, About).
   */
  navLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Primary logo (shown on cream/light backgrounds).
   */
  logo?: (number | null) | Media;
  /**
   * Logo for dark/burgundy backgrounds.
   */
  logoDark?: (number | null) | Media;
  /**
   * Brand card image shown in the footer lower band.
   */
  footerImage?: (number | null) | Media;
  copyrightYear: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero?: {
    headline?: string | null;
    /**
     * Words within the headline to render in gold accent. Must match part of the headline exactly.
     */
    headlineEmphasis?: string | null;
    tagline?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
    /**
     * Poster / static fallback image shown under the video and for reduced-motion.
     */
    heroImage?: (number | null) | Media;
    /**
     * Full-bleed muted looping background video (mp4/webm). Falls back to hero image when empty.
     */
    heroVideo?: (number | null) | Media;
  };
  intro?: {
    headline?: string | null;
    body?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
    image?: (number | null) | Media;
  };
  marquee?: {
    /**
     * Fallback portrait when a marquee item has no image. Prefer per-item images on Marquee Items.
     */
    image?: (number | null) | Media;
  };
  /**
   * Word + image clusters that scroll together (Figma Social → Cultured → Curated).
   */
  marqueeWords?:
    | {
        word: string;
        /**
         * Portrait paired with this word (slides with the text).
         */
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  story?: {
    headline?: string | null;
    body?: string | null;
    image?: (number | null) | Media;
  };
  featuredWork?: {
    headline?: string | null;
    /**
     * Select up to 3 case studies to feature on the homepage (Figma order).
     */
    works?: (number | Work)[] | null;
  };
  quoteBand?: {
    quote?: string | null;
    attribution?: string | null;
  };
  /**
   * Client testimonials shown in the carousel.
   */
  testimonials?:
    | {
        name: string;
        role?: string | null;
        quote: string;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  finalCta?: {
    headline?: string | null;
    subtext?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "studio-page".
 */
export interface StudioPage {
  id: number;
  hero?: {
    headline?: string | null;
    tagline?: string | null;
    image?: (number | null) | Media;
  };
  servicesSection?: {
    title?: string | null;
  };
  /**
   * Stacked service cards on the Studio page.
   */
  services?:
    | {
        /**
         * e.g. Service 01 - The Thryve Blueprint
         */
        serviceLabel: string;
        /**
         * Internal service name, e.g. The Thryve Blueprint
         */
        title: string;
        /**
         * Large display title before accent, e.g. Strategy & Con
         */
        displayTitlePrefix: string;
        /**
         * Accent portion overlaid on image stack, e.g. sulting
         */
        displayTitleAccent: string;
        description?: string | null;
        includes?:
          | {
              item: string;
              id?: string | null;
            }[]
          | null;
        stackImages?:
          | {
              image: number | Media;
              id?: string | null;
            }[]
          | null;
        ctaLabel?: string | null;
        ctaHref?: string | null;
        id?: string | null;
      }[]
    | null;
  howItWorksSection?: {
    title?: string | null;
  };
  howItWorks?:
    | {
        step: number;
        title: string;
        description?: string | null;
        /**
         * Image displayed when this step is active
         */
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  cta?: {
    headline?: string | null;
    subtext?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works-page".
 */
export interface WorksPage {
  id: number;
  hero?: {
    headline?: string | null;
    subheadline?: string | null;
    /**
     * Decorative backdrop image on the right side of the hero.
     */
    heroImage?: (number | null) | Media;
  };
  portfolio?: {
    title?: string | null;
  };
  cta?: {
    headline?: string | null;
    subtext?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-page".
 */
export interface JournalPage {
  id: number;
  hero?: {
    headline?: string | null;
    tagline?: string | null;
    image?: (number | null) | Media;
  };
  entriesSection?: {
    title?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  hero?: {
    headline?: string | null;
    /**
     * Italic champagne line below the headline.
     */
    tagline?: string | null;
    image?: (number | null) | Media;
  };
  founderSection?: {
    headline?: string | null;
    name?: string | null;
    title?: string | null;
    bio?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Primary founder portrait.
     */
    image?: (number | null) | Media;
  };
  founderStory?: {
    headlineLead?: string | null;
    headlineMuted?: string | null;
    headlineEnd?: string | null;
    paragraphOne?: string | null;
    paragraphTwo?: string | null;
    storyImage?: (number | null) | Media;
    /**
     * Three images arranged in the staggered collage.
     */
    photos?:
      | {
          photo: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  founderQuote?: {
    quote?: string | null;
    attribution?: string | null;
  };
  whatThryve?: {
    intro?: string | null;
    agencyCopy?: string | null;
    aspirationCopy?: string | null;
    image?: (number | null) | Media;
  };
  cta?: {
    headline?: string | null;
    subtext?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  hero?: {
    headline?: string | null;
    body?: string | null;
    image?: (number | null) | Media;
  };
  form?: {
    heading?: string | null;
    intro?: string | null;
    nameLabel?: string | null;
    emailLabel?: string | null;
    serviceLabel?: string | null;
    brandNameLabel?: string | null;
    socialLinkLabel?: string | null;
    challengeLabel?: string | null;
    brandGoalLabel?: string | null;
    timelineLabel?: string | null;
    referralLabel?: string | null;
    additionalNotesLabel?: string | null;
    submitLabel?: string | null;
    successTitle?: string | null;
    successBody?: string | null;
    serviceOptions?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    timelineOptions?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    referralOptions?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  location?: T;
  email?: T;
  phone?: T;
  bookingLink?: T;
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  logo?: T;
  logoDark?: T;
  footerImage?: T;
  copyrightYear?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        headlineEmphasis?: T;
        tagline?: T;
        ctaLabel?: T;
        ctaHref?: T;
        heroImage?: T;
        heroVideo?: T;
      };
  intro?:
    | T
    | {
        headline?: T;
        body?: T;
        ctaLabel?: T;
        ctaHref?: T;
        image?: T;
      };
  marquee?:
    | T
    | {
        image?: T;
      };
  marqueeWords?:
    | T
    | {
        word?: T;
        image?: T;
        id?: T;
      };
  story?:
    | T
    | {
        headline?: T;
        body?: T;
        image?: T;
      };
  featuredWork?:
    | T
    | {
        headline?: T;
        works?: T;
      };
  quoteBand?:
    | T
    | {
        quote?: T;
        attribution?: T;
      };
  testimonials?:
    | T
    | {
        name?: T;
        role?: T;
        quote?: T;
        image?: T;
        id?: T;
      };
  finalCta?:
    | T
    | {
        headline?: T;
        subtext?: T;
        ctaLabel?: T;
        ctaHref?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "studio-page_select".
 */
export interface StudioPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        tagline?: T;
        image?: T;
      };
  servicesSection?:
    | T
    | {
        title?: T;
      };
  services?:
    | T
    | {
        serviceLabel?: T;
        title?: T;
        displayTitlePrefix?: T;
        displayTitleAccent?: T;
        description?: T;
        includes?:
          | T
          | {
              item?: T;
              id?: T;
            };
        stackImages?:
          | T
          | {
              image?: T;
              id?: T;
            };
        ctaLabel?: T;
        ctaHref?: T;
        id?: T;
      };
  howItWorksSection?:
    | T
    | {
        title?: T;
      };
  howItWorks?:
    | T
    | {
        step?: T;
        title?: T;
        description?: T;
        image?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        subtext?: T;
        ctaLabel?: T;
        ctaHref?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works-page_select".
 */
export interface WorksPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        subheadline?: T;
        heroImage?: T;
      };
  portfolio?:
    | T
    | {
        title?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        subtext?: T;
        ctaLabel?: T;
        ctaHref?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-page_select".
 */
export interface JournalPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        tagline?: T;
        image?: T;
      };
  entriesSection?:
    | T
    | {
        title?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        tagline?: T;
        image?: T;
      };
  founderSection?:
    | T
    | {
        headline?: T;
        name?: T;
        title?: T;
        bio?: T;
        image?: T;
      };
  founderStory?:
    | T
    | {
        headlineLead?: T;
        headlineMuted?: T;
        headlineEnd?: T;
        paragraphOne?: T;
        paragraphTwo?: T;
        storyImage?: T;
        photos?:
          | T
          | {
              photo?: T;
              id?: T;
            };
      };
  founderQuote?:
    | T
    | {
        quote?: T;
        attribution?: T;
      };
  whatThryve?:
    | T
    | {
        intro?: T;
        agencyCopy?: T;
        aspirationCopy?: T;
        image?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        subtext?: T;
        ctaLabel?: T;
        ctaHref?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  hero?:
    | T
    | {
        headline?: T;
        body?: T;
        image?: T;
      };
  form?:
    | T
    | {
        heading?: T;
        intro?: T;
        nameLabel?: T;
        emailLabel?: T;
        serviceLabel?: T;
        brandNameLabel?: T;
        socialLinkLabel?: T;
        challengeLabel?: T;
        brandGoalLabel?: T;
        timelineLabel?: T;
        referralLabel?: T;
        additionalNotesLabel?: T;
        submitLabel?: T;
        successTitle?: T;
        successBody?: T;
        serviceOptions?:
          | T
          | {
              label?: T;
              id?: T;
            };
        timelineOptions?:
          | T
          | {
              label?: T;
              id?: T;
            };
        referralOptions?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}