/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    works: Work;
    'journal-posts': JournalPost;
    'contact-inquiries': ContactInquiry;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    works: WorksSelect<false> | WorksSelect<true>;
    'journal-posts': JournalPostsSelect<false> | JournalPostsSelect<true>;
    'contact-inquiries': ContactInquiriesSelect<false> | ContactInquiriesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'studio-page': StudioPage;
    'works-page': WorksPage;
    'journal-page': JournalPage;
    'about-page': AboutPage;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'studio-page': StudioPageSelect<false> | StudioPageSelect<true>;
    'works-page': WorksPageSelect<false> | WorksPageSelect<true>;
    'journal-page': JournalPageSelect<false> | JournalPageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works".
 */
export interface Work {
  id: number;
  title: string;
  /**
   * URL-safe identifier (e.g. casa-muse). Used in /works/[slug].
   */
  slug: string;
  client: string;
  /**
   * Short brand tagline shown on the case study hero.
   */
  tagline?: string | null;
  /**
   * Service tags shown on the case study card (e.g. Branding, Strategy).
   */
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  heroImage?: (number | null) | Media;
  /**
   * Thumbnail shown on the Works listing page.
   */
  coverImage?: (number | null) | Media;
  overview?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  problem?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  solution?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  feedback?: {
    quote?: string | null;
    /**
     * Name and role, e.g. Jane D., Founder of CASA MUSE
     */
    attribution?: string | null;
  };
  galleryImages?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Lower numbers appear first on the Works page.
   */
  sortOrder?: number | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-posts".
 */
export interface JournalPost {
  id: number;
  title: string;
  /**
   * URL-safe identifier. Used in /journal/[slug].
   */
  slug: string;
  /**
   * e.g. Branding, Strategy, Creative Obsession
   */
  category: string;
  /**
   * Estimated read time in minutes.
   */
  readTime?: number | null;
  author?: string | null;
  /**
   * Short summary shown on the Journal listing grid.
   */
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  publishedAt: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-inquiries".
 */
export interface ContactInquiry {
  id: number;
  name: string;
  email: string;
  subject?: string | null;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'works';
        value: number | Work;
      } | null)
    | ({
        relationTo: 'journal-posts';
        value: number | JournalPost;
      } | null)
    | ({
        relationTo: 'contact-inquiries';
        value: number | ContactInquiry;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works_select".
 */
export interface WorksSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  client?: T;
  tagline?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  heroImage?: T;
  coverImage?: T;
  overview?: T;
  problem?: T;
  solution?: T;
  feedback?:
    | T
    | {
        quote?: T;
        attribution?: T;
      };
  galleryImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  sortOrder?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-posts_select".
 */
export interface JournalPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  readTime?: T;
  author?: T;
  excerpt?: T;
  heroImage?: T;
  body?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-inquiries_select".
 */
export interface ContactInquiriesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  subject?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  tagline?: string | null;
  location?: string | null;
  email?: string | null;
  phone?: string | null;
  /**
   * URL for the 'Book a Call' CTA button in the nav.
   */
  bookingLink?: string | null;
  /**
   * Main navigation links (Studio, Works, Journal, About).
   */
  navLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  footerLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Primary logo (shown on cream/light backgrounds).
   */
  logo?: (number | null) | Media;
  /**
   * Logo for dark/burgundy backgrounds.
   */
  logoDark?: (number | null) | Media;
  copyrightYear: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero?: {
    headline?: string | null;
    /**
     * Words within the headline to render in gold accent. Must match part of the headline exactly.
     */
    headlineEmphasis?: string | null;
    tagline?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
    heroImage?: (number | null) | Media;
  };
  intro?: {
    headline?: string | null;
    body?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  /**
   * Words that scroll across the marquee strip between sections.
   */
  marqueeWords?:
    | {
        word: string;
        id?: string | null;
      }[]
    | null;
  story?: {
    headline?: string | null;
    body?: string | null;
    image?: (number | null) | Media;
  };
  featuredWork?: {
    headline?: string | null;
    /**
     * Select up to 4 case studies to feature on the homepage.
     */
    works?: (number | Work)[] | null;
  };
  quoteBand?: {
    quote?: string | null;
    attribution?: string | null;
  };
  /**
   * Client testimonials shown in the carousel.
   */
  testimonials?:
    | {
        name: string;
        role?: string | null;
        quote: string;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  finalCta?: {
    headline?: string | null;
    subtext?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "studio-page".
 */
export interface StudioPage {
  id: number;
  hero?: {
    headline?: string | null;
    tagline?: string | null;
  };
  /**
   * Stacked service cards on the Studio page.
   */
  services?:
    | {
        /**
         * e.g. The Thryve Blueprint
         */
        title: string;
        /**
         * Short descriptor shown on the card.
         */
        tagline?: string | null;
        description?: string | null;
        includes?:
          | {
              item: string;
              id?: string | null;
            }[]
          | null;
        image?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  howItWorks?:
    | {
        step: number;
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    headline?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works-page".
 */
export interface WorksPage {
  id: number;
  hero?: {
    headline?: string | null;
    tagline?: string | null;
  };
  cta?: {
    headline?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-page".
 */
export interface JournalPage {
  id: number;
  hero?: {
    headline?: string | null;
    tagline?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  hero?: {
    headline?: string | null;
    tagline?: string | null;
  };
  founderSection?: {
    headline?: string | null;
    name?: string | null;
    title?: string | null;
    bio?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Primary founder portrait.
     */
    image?: (number | null) | Media;
  };
  founderStory?: {
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Images arranged in the collage grid alongside the story text.
     */
    photos?:
      | {
          photo: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  founderQuote?: {
    quote?: string | null;
    attribution?: string | null;
  };
  whatThryve?: {
    headline?: string | null;
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  cta?: {
    headline?: string | null;
    ctaLabel?: string | null;
    ctaHref?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  location?: T;
  email?: T;
  phone?: T;
  bookingLink?: T;
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  footerLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  logo?: T;
  logoDark?: T;
  copyrightYear?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        headlineEmphasis?: T;
        tagline?: T;
        ctaLabel?: T;
        ctaHref?: T;
        heroImage?: T;
      };
  intro?:
    | T
    | {
        headline?: T;
        body?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  marqueeWords?:
    | T
    | {
        word?: T;
        id?: T;
      };
  story?:
    | T
    | {
        headline?: T;
        body?: T;
        image?: T;
      };
  featuredWork?:
    | T
    | {
        headline?: T;
        works?: T;
      };
  quoteBand?:
    | T
    | {
        quote?: T;
        attribution?: T;
      };
  testimonials?:
    | T
    | {
        name?: T;
        role?: T;
        quote?: T;
        image?: T;
        id?: T;
      };
  finalCta?:
    | T
    | {
        headline?: T;
        subtext?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "studio-page_select".
 */
export interface StudioPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        tagline?: T;
      };
  services?:
    | T
    | {
        title?: T;
        tagline?: T;
        description?: T;
        includes?:
          | T
          | {
              item?: T;
              id?: T;
            };
        image?: T;
        id?: T;
      };
  howItWorks?:
    | T
    | {
        step?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "works-page_select".
 */
export interface WorksPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        tagline?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "journal-page_select".
 */
export interface JournalPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        tagline?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        tagline?: T;
      };
  founderSection?:
    | T
    | {
        headline?: T;
        name?: T;
        title?: T;
        bio?: T;
        image?: T;
      };
  founderStory?:
    | T
    | {
        body?: T;
        photos?:
          | T
          | {
              photo?: T;
              id?: T;
            };
      };
  founderQuote?:
    | T
    | {
        quote?: T;
        attribution?: T;
      };
  whatThryve?:
    | T
    | {
        headline?: T;
        body?: T;
      };
  cta?:
    | T
    | {
        headline?: T;
        ctaLabel?: T;
        ctaHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}